name: Gradle Test on Pull Request

on:
  pull_request:
    branches:
      - main  # Change to your main branch, e.g., 'master' if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11  
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew clean test

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
